services:
  nestjs:
    build:
      context: ./marketplace-nestjs
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./marketplace-nestjs:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: pnpm run start:dev
    # command: pnpm run start:debug
    container_name: marketplace-nestjs
